# Generated by Django 5.1.3 on 2024-12-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('corral', models.CharField(max_length=150)),
            ],
        ),
    ]
