# Generated by Django 5.1.3 on 2024-12-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=150)),
            ],
        ),
    ]
