# Generated by Django 5.1.3 on 2024-12-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0002_corral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('corral', models.CharField(max_length=150)),
            ],
        ),
    ]
