# Generated by Django 5.1.3 on 2024-12-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0005_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('id_ganado', models.CharField(max_length=150)),
            ],
        ),
    ]
